env: "local" # 'local', 'dev', 'prod'

grpc_server:
  port: 50051
  web_port: 50052

url_shortener:
  alias_length: 4
  base_url: "http://localhost:8080"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "${DATABASE_PASSWORD}"
  dbname: "gurls"
  sslmode: "disable"
  timezone: "UTC"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "1h"
  # Migration settings for local development
  auto_migrate: true  # Automatically run migrations on startup
  seed_data: true     # Seed initial data (subscription types)

payment:
  shop_id: "test-shop-id"
  secret_key: "test-secret-key"
  api_url: "https://api.yookassa.ru/v3"
  test_mode: true  # Enable mock payment mode for development
