env: "local" # 'local', 'dev', 'prod'

grpc_server:
  port: 50051

url_shortener:
  alias_length: 4

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "${DATABASE_PASSWORD}"
  dbname: "gurls"
  sslmode: "disable"
  timezone: "UTC"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "1h"
  # Migration settings for local development
  auto_migrate: true  # Automatically run migrations on startup
  seed_data: true     # Seed initial data (subscription types)
